name: Deploy (swm)
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        run: |
          set -ex

          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          export TERM=xterm

          ssh -t -t -o 'StrictHostKeyChecking no' "${{ secrets.SSH_LOGIN_USER }}@${{ secrets.SSH_HOST }}" \
            "grep "^docker:" /etc/group | sed -e 's/^[^:]\+:[^:]\+:\([^:]\+\):[^:]\+$/\1/g'" > gid

          REMOTE_DOCKER_GID=$(echo $(tail -n 1 gid) | sed -e 's/\r//g')

          docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          docker build \
            --build-arg \
              HOST_DOCKER_GROUP_ID=$REMOTE_DOCKER_GID \
            --rm --no-cache --tag ${{ secrets.DOCKER_HUB_USERNAME }}/swift-playground .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/swift-playground

          ssh -t -t -o 'StrictHostKeyChecking no' "${{ secrets.SSH_LOGIN_USER }}@${{ secrets.SSH_HOST }}" <<EOF
          set -ex

          [ -d app ] || git clone https://github.com/taketo1024/swift-playground.git app

          cd app
          git pull --rebase origin taketo1024/swm

          sudo chmod 666 /var/run/docker.sock
          chmod 773 Resources/Temp

          echo GOOGLE_CLOUD_PLATFORM_PROJECT_ID=${{ secrets.GOOGLE_CLOUD_PLATFORM_PROJECT_ID }} > .env
          echo FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }} > .env
          echo FIREBASE_REFRESH_TOKEN=${{ secrets.FIREBASE_REFRESH_TOKEN }} >> .env

          docker_compose='docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v "\$PWD:\$PWD" -w="\$PWD" docker/compose:latest'
          eval \$docker_compose --file docker-compose-swm.yml pull
          eval \$docker_compose --file docker-compose-swm.yml  up --detach app carbonara

          docker image prune --force

          exit 0
          EOF
