name: Run (swm)
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Docker Images (swm)"]
    types:
      - completed

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: |
          set -ex

          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          TERM=xterm ssh -t -t -o 'StrictHostKeyChecking no' "${{ secrets.SSH_LOGIN_USER }}@${{ secrets.SSH_HOST }}" <<EOF
          set -ex

          [ -d app ] || git clone https://github.com/taketo1024/swift-playground.git app

          cd app
          git pull --rebase origin taketo1024/swm
          
          docker_compose='docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v "\$PWD:\$PWD" -w="\$PWD" docker/compose:latest'
          eval \$docker_compose --file docker-compose-swm.yml pull
          eval \$docker_compose --file docker-compose-swm.yml up --detach app carbonara

          docker image prune --force

          exit 0
          EOF
